sudo: required
services:
- docker
env:
  global:
  - secure: B+Qzn/MFXf2yYPwpLeR29q1jJprw6cUQiRopOQG4fp0t1L1ccvwu1eu/khcvyjqXZoyc87NTXLAE04p6h0MMVhK7Mkdw4FXFhXJvAUmCwAcdgWfp3R8I0i8lzNj4JOIzB41T2Ebf6cx4GTZ6B4FHN6py0t7iv4FyeUl5cRb2B1TUcPj/sJNARXUr8i6ZoG/axUcYcuoRSAzSW+slgXzug0c5fXgJD16EE/MXrHPM/jOolKeV8+KbYn+65aS44DqWTf+S4BtR53HGcyIlZD20p4tU7sc70UKo9+egStz22rUQc29sC/3KVyR+8my8hecYvLLpzUudWsz8b95vXKN51a9QZWO8ETq5Le7G+eWGwQnMBLMnzh7+mypSRUGt/jkWcSk8eI+m1ZQmsk0byzRelB8AbF5N/SzfVU1II+Coaj25XxLTpyR32wUyq4Y+kjL01oa7DgWHk8J2t76REW7uiCtYO/nKyRZydaOEGWXR4ZM4ZXIZ5Vrhzm6l3guayFDoz+YoBrOe3FOWA5SBIV1CeRsTcow55B0TaVI/D8S46UArZZ4/u/1YOu200nFh4xfrq3VsTfT+hWnsEPXQxVyjYh/tRgF7s87f0c6zsU2aA0QoiVTBd1/In5n1Cs0H5dym+7UqnvxR/lDhOmU7xzFSXUnizm3Ul71hUzabO2W88MY=
  - secure: f5wIWgcOeUTiurRiiuJwTNDHdaNIfQs9Iq9L+43EC66nj5tQMLbAIO3HS/Fx621EIbELBkt0Y4wo0GyqNN3MzyVIGf0QDCgRBL5kOGCEvgDBpifesX32f8g+TON8FaK7Vi7IVJPP8YsKqcQRc+egJa9GINSB8biSdBgcFLjl8fYJ7GFhsT/unDv7H5f3aqh9Bx/jVm7pS8iYH/sqCHRKRMVX75OltsLHUMMifoN504gfRzCznUmKQcmVAdoOumZzLeBzRxsGEADLWZSiLsRrjeg/IclpJha3/PdIO19+MKu+X6L9qNX1vzRQ11K7YzqzZXRaXMLH6WOAfi7R86E4ON1ucebn2aKKXmWQd30p+LOfWfUVnXdLWwVKZYSv66JbDpaUPqGBvCi9jKYKKcOg495DHLTC4XzkB6LwQT1Eq7/YDMNoUrwEUgTyYneZE3n2oZFJJuEvujrRFi4VMkN44+XZ1WMCISZ0li72mkFUMkH70ZWt5dppgNsxUGYzcc8ATN6vQESz+lUOd42lrje+lB0sazO4eV7XAzQLUnuNOBp9msJzK4p6SgjAuS5ezGUMrHJYxFr2/wYghvrR6dYFCMxBzPY/TDz7W9eJ+HHfmVPn5nY/dOcxPMdZPugaECPxYHIlPGkqbYM0cV8tiUr8ndz/FnQ5IvEfYec6ZE88yZM=
script:
- docker build -t $DOCKER_USER/go-hello:latest -t $DOCKER_USER/go-hello:$TRAVIS_COMMIT .
deploy:
  provider: script
  script:
  - ls -lah
  - echo hey, pushing image for user $DOCKER_USER
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker images
  - docker push $DOCKER_USER/go-hello
  on:
    branch: master
